[ALPS11034563] fix bt build error
[Description]
vendor/mediatek/kernel_modules/connectivity/bt/linux_v2/include/btmtk_define.h:124:9: error: MIN macro redefined [-Werror,-Wmacro-redefined]
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
        ^
kernel-6.1/include/linux/minmax.h:314:9: note: previous definition is here
#define MIN(a, b) __cmp(min, a, b)

[Test]
Build Pass

MTK-Commit-Id: 245f4e7c3d09849f164f5a5c9dc6f655271ea06c

(cherry picked from commit 14cdb877f69d002d40e357dc1766d7f1ee4c15bb)
Signed-off-by: Liangjun Kuang <ot_liangjun.kuang@mediatek.com>
CR-Id: ALPS11034563
Feature: Kernel SI Operation
Change-Id: I8fe753e37c0ef2fd98d05b8e0670a6c76133582f
Reviewed-on: https://gerrit.mediatek.inc/c/neptune/bt_driver/linux_v2/+/11834088
Commit-Check: srv_check_service <srv_check_service@mediatek.com>
Build: srv_preflight_b001 <srv_preflight_b001@mediatek.com>
AutoUT-Review-Label: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Tested-by: ot_huangcong.huang <ot_huangcong.huang@mediatek.com>
Local-Test: srv_pdas <srv_pdas@mediatek.com>
Reviewed-by: simfex.chiu <simfex.chiu@mediatek.com>
Reviewed-by: bo.ye <bo.ye@mediatek.com>