[ALPS11034563] fix bt build error
[Description]
vendor/mediatek/kernel_modules/connectivity/bt/linux_v2_mt6653/include/btmtk_define.h:124:9: error: MIN macro redefined [-Werror,-Wmacro-redefined]
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
        ^
kernel-6.1/include/linux/minmax.h:314:9: note: previous definition is here
#define MIN(a, b) __cmp(min, a, b)

[Test]
Build pass

MTK-Commit-Id: 8df504305ea46772e4029e52970399417785e6bc

(cherry picked from commit 1b513095033727213a7719f569ab5952c0b9a52a)
Signed-off-by: Liangjun Kuang <ot_liangjun.kuang@mediatek.com>
CR-Id: ALPS11034563
Feature: Kernel SI Operation
Change-Id: I27467b534a8e1fe26f407c0d65faf0cd95d71eb0